#!/usr/bin/env python3
"""Find the STEP tables in a procurement plan rendition and read their columns.

A procurement plan document is two things bolted together, and only one of them
is data. The front is narrative the borrower writes: thresholds, national
arrangements, preambles, sometimes whole annex tables of its own in its own
language. The back is generated by STEP, and it is always the same five
sections in the same order - WORKS, GOODS, NON CONSULTING SERVICES, CONSULTING
FIRMS, INDIVIDUAL CONSULTANTS - each with the same columns under the same
English headings, whatever language the rest of the document is in.

That invariant is the whole design. Every one of the 496 renditions in the
eight-country corpus carries all five section headings and the "Activity
Reference No." column heading, with no exceptions, so the table can be located
exactly rather than inferred, and everything outside it can be ignored rather
than defended against. The parser this replaces read the whole document with
regexes and paid for it: a narrative paragraph that happened to contain a date
and a number looked exactly like a table row.

Two renditions of the same plan can be laid out completely differently, because
the layout is the text extractor's, not the borrower's:

  gutters    The table prints at fixed character positions, columns separated
             by runs of spaces, each cell wrapped over as many physical lines
             as it needs. 474 of 496 renditions. Read by slicing every line of
             a record on that document's own column boundaries.

  collapsed  Whitespace is gone. Each cell is on its own line, or a few narrow
             cells share one. 22 of 496 renditions - but they are the NEWEST
             rendition for six of the eight projects, so they decide what the
             current-state table says, and being 4% of documents does not make
             them a tail case.

Column boundaries are not guessed. The headings give the order, which is fixed,
and their positions give a coarse x; the data rows give the exact edge, because
a gutter in a fixed-width table is blank on every line. Neither signal is
sufficient alone: heading labels are centred over their columns and butt
against each other with a single space on the right-hand side of the table,
while data gutters close whenever a long description overflows.
"""
import re
import unicodedata

SECTION_NAMES = ("WORKS", "GOODS", "NON CONSULTING SERVICES",
                 "CONSULTING FIRMS", "INDIVIDUAL CONSULTANTS")
SECTION_RE = re.compile(
    r"^\s*(" + "|".join(n.replace(" ", r"[- ]") for n in SECTION_NAMES) + r")\s*$",
    re.I)
ANCHOR_RE = re.compile(r"Activity Reference No")

# A data row begins where the first column holds a borrower reference. The
# reference is the only thing that reliably starts a record: STEP prints it
# first in the first column of every row of every section.
ROW_START_RE = re.compile(
    r"^\s*([A-Z][A-Z0-9]{1,}(?:[-–—]\s?[A-Z0-9]+){1,6})\s*(/|$)")

# The STEP columns, in print order, per section. A rendition may break a
# heading across lines, and omits columns the plan does not use, but it never
# reorders or renames them - which is why order alone resolves an ambiguous
# heading match, and why a catalogue is enough without a per-borrower rule.
_BASE = [
    ("borrower_ref", "Activity Reference No."),
    ("loan", "Loan / Credit No."),
    ("component", "Component"),
    ("review_type", "Review Type"),
    ("method_raw", "Method"),
    ("market_approach", "Market Approach"),
]
_GOODS_TAIL = [
    ("procurement_process", "Procurement Process"),
    ("prequalification", "Prequalification (Y/N)"),
    ("sea_sh_risk", "High SEA/SH Risk"),
    ("procurement_doc_type", "Procurement Document Type"),
]
_CONSULTING_TAIL = [("contract_type", "Contract Type")]
_MONEY = [
    ("estimated_amount", "Estimated Amount (US$)"),
    ("actual_amount", "Actual Amount (US$)"),
    ("status_raw", "Process Status"),
]
# The first milestone heading of each section. Nothing is read out of the
# milestone columns, but the leftmost one has to be found: it is what bounds
# the Process Status column on the right, and without it a status cell runs on
# into a column of dates.
_MILESTONES = {
    "WORKS": ["Draft Pre-qualification Documents", "Prequalification Evaluation Report",
              "Draft Bidding Document / Justification"],
    "GOODS": ["Draft Pre-qualification Documents", "Prequalification Evaluation Report",
              "Draft Bidding Document / Justification"],
    "NON CONSULTING SERVICES": ["Draft Pre-qualification Documents", "Terms of Reference",
                                "Expression of Interest", "Short List"],
    "CONSULTING FIRMS": ["Terms of Reference", "Expression of Interest", "Short List"],
    "INDIVIDUAL CONSULTANTS": ["Terms of Reference", "Invitation to Identified",
                               "Draft Negotiated Contract"],
}


def catalogue(section):
    """The ordered column catalogue for a section: a superset, not a schema.

    A superset because the same section is printed with different columns in
    different plans - a third of NON CONSULTING SERVICES tables carry the
    consulting columns - and because 19% of renditions have no Estimated Amount
    column at all, those being old enough that STEP printed only the actual. A
    reader that demanded a fixed column list would reject them; one that takes
    what it finds, in order, reads them.
    """
    section = section.upper()
    tail = _CONSULTING_TAIL if section in ("CONSULTING FIRMS", "INDIVIDUAL CONSULTANTS") \
        else _GOODS_TAIL + _CONSULTING_TAIL
    milestones = [(f"_milestone_{i}", m)
                  for i, m in enumerate(_MILESTONES.get(section, []))]
    return _BASE + tail + _MONEY + milestones


class Table:
    """One section's table in one rendition: its heading band and its rows."""

    def __init__(self, section, start, header, data):
        self.section = section
        self.start = start
        self.header = header
        self.data = data

    def __repr__(self):
        return (f"<Table {self.section} @{self.start} "
                f"header={len(self.header)} data={len(self.data)}>")


def find_tables(lines, max_header=22):
    """Every STEP table in the rendition, in document order.

    A section heading is a line holding nothing but the section's name AND
    followed within three lines by the "Activity Reference No." column heading.
    The second half of that test is load-bearing: "GOODS" and "WORKS" also
    occur alone on a line in the narrative, and on the corpus the name alone
    over-counts by up to 4,000 headings in a single document.

    Headings repeat. Some renditions reprint the whole section heading and
    column band on every page, which is why this returns a table per occurrence
    rather than five per document and lets the caller's own de-duplication
    handle the repeats - a package that appears twice with identical content is
    already one row downstream.
    """
    tables = []
    heads = [i for i, l in enumerate(lines)
             if SECTION_RE.match(l)
             and any(ANCHOR_RE.search(x) for x in lines[i + 1:i + 4])]
    for n, i in enumerate(heads):
        end = heads[n + 1] if n + 1 < len(heads) else len(lines)
        # The heading band runs to the first data row; everything after it, up
        # to the next heading, is rows.
        split = None
        for j in range(i + 1, min(i + max_header, end)):
            if ROW_START_RE.match(lines[j]):
                split = j
                break
        if split is None:
            split = min(i + max_header, end)
        section = re.sub(r"\s+", " ", SECTION_RE.match(lines[i]).group(1).upper())
        section = section.replace("NON-CONSULTING", "NON CONSULTING")
        tables.append(Table(section, i, lines[i:split], lines[split:end]))
    return tables


def is_collapsed(table):
    """Has this rendition thrown the column positions away?

    Measured on the heading band rather than the rows, because an empty section
    has no rows and a section whose every description is short has few wide
    lines. A band that still prints its headings side by side kept its columns.
    """
    wide = sum(1 for l in table.header if len(re.findall(r"\S {2,}\S", l)) >= 3)
    return wide < 2


def _label_positions(header, label, min_prefix=5):
    """Every x at which `label` might begin in the heading band.

    A heading is broken across lines at a point that depends on the column's
    width in this particular rendition - "Estimated Am" over "ount (US$)" in
    one, "Estimated Amo" over "unt (US$)" in another - so the whole label is
    rarely present on any one line. The longest prefix that IS present locates
    it. Every occurrence is returned, not the first: which one is correct is
    decided later, by order, and deciding it here would need a tie-break this
    function has no information for.
    """
    for n in range(len(label), min_prefix - 1, -1):
        frag = label[:n]
        hits = [(l.find(frag, k), n) for l in header
                for k in [0] if frag in l]
        hits = []
        for line in header:
            k = line.find(frag)
            while k >= 0:
                hits.append((k, n))
                k = line.find(frag, k + 1)
        if hits:
            return sorted(set(hits))
    return []


def solve_columns(header, section):
    """Assign catalogue columns to x positions, left to right.

    The constraint that makes this reliable is that STEP prints the columns in
    a fixed order, so a valid assignment is one whose x positions increase.
    Without it, a prefix match is ambiguous in exactly the way that matters:
    "Contract Type" and "Contract Completion" share nine characters, and
    "Contract Completion" sits at the far right of the table where a Contract
    Type column has no business being.

    Longest-increasing-subsequence over the catalogue, scored first on how many
    columns are placed and then on how much of each label was actually matched,
    so a full-label match is preferred to a prefix of it.
    """
    cols = catalogue(section)
    candidates = [(field, _label_positions(header, label)) for field, label in cols]
    best = {}          # x of last placed column -> (placed, matched_chars, [(field, x)])
    best[-1] = (0, 0, [])
    for field, positions in candidates:
        nxt = dict(best)
        for last_x, (placed, chars, chosen) in best.items():
            for x, n in positions:
                if x <= last_x:
                    continue
                cand = (placed + 1, chars + n, chosen + [(field, x)])
                if x not in nxt or cand[:2] > nxt[x][:2]:
                    nxt[x] = cand
        best = nxt
    placed, chars, chosen = max(best.values(), key=lambda v: (v[0], v[1]))
    return chosen


def column_spans(table, section, min_starts=2):
    """Turn the solved label positions into [start, end) character spans.

    The label's x is not the column's edge. STEP centres a heading over its
    column, so slicing at the label position clips the left of every cell under
    it - on one Nigerian table the Loan cell begins two characters before its
    own heading does.

    The edge is read off the rows instead, from where their cells START. For
    each position, count the rows on which a run of text begins there: a line
    is blank at p-1 and not blank at p. A left-aligned column puts every one of
    its cells at exactly its own left edge, so that count spikes there and
    nowhere near it, and the spike is the edge.

    This replaced looking for the blank gutter between the columns, which is
    the obvious thing and does not work. Two reasons, both fatal and both seen
    on the corpus. The gutter between the description and the loan is often a
    single character wide and is closed by any description that fills its
    column, so on a real table there is no run of blank to find. And inside a
    column whose cells are mostly short, the unused right-hand part is blank on
    more rows than the true gutter is, so the blankest position in the interval
    lies in the middle of a column rather than between two - which silently
    merges that column with its neighbour and shifts every column after it.

    Amount columns are right-aligned and so have no single start position. They
    still work, because what is needed is a position no cell begins to the left
    of, and the leftmost of their starts is one: the column is read slightly
    narrow and nothing is clipped.
    """
    chosen = solve_columns(table.header, section)
    if not chosen:
        return []
    rows = [l for l in table.data if l.strip()]
    width = max([len(l) for l in rows] + [len(l) for l in table.header] + [1])
    padded = [l.ljust(width + 1) for l in rows]
    # A cell edge is a run of text that begins after a GAP, not after a single
    # space. Counting every word boundary instead puts a spike inside every
    # multi-word cell - "Component 4: Project" offers one at the "4:" - and the
    # tie-break then lands the column edge in the middle of the cell before it.
    starts = [0] * (width + 1)
    for line in padded:
        for p in range(2, width):
            if line[p] != " " and line[p - 1] == " " and line[p - 2] == " ":
                starts[p] += 1

    xs = [x for _, x in chosen]
    bounds = [0]
    for left, right in zip(xs, xs[1:]):
        lo, hi = left + 1, min(right + 1, width)
        best, best_p = 0, None
        for p in range(lo, hi):
            if starts[p] >= best and starts[p] >= min_starts:
                best, best_p = starts[p], p        # ties resolve rightwards
        # A column that is empty in every row of this table offers no start to
        # find. The midpoint is then as good as anything and costs only the
        # width of a column nothing is read out of.
        bounds.append(best_p if best_p is not None else (left + right) // 2)
    bounds.append(width)
    return [(field, bounds[i], bounds[i + 1]) for i, (field, _) in enumerate(chosen)]


def _assemble(pieces):
    """Rebuild one cell from its slices, in line order.

    A cell too wide for its column wraps, and the rendition gives no marker for
    where. The break point itself is the signal: a piece that reaches the
    column's right edge was cut mid-word and its successor glues on, while one
    that stops short broke at a space and its successor needs one. Getting this
    wrong is not cosmetic - it is the difference between "Pending
    Implementation" and "PendingImplementation", and between a description that
    can be read and one that cannot.

    `pieces` is (text, reached_right_edge) per line, already stripped of the
    lines that held nothing in this column.
    """
    out, glue = "", False
    for text, filled in pieces:
        if not out:
            out = text
        elif glue:
            out += text
        else:
            out += " " + text
        glue = filled
    return out


def read_gutter_table(table):
    """Rows out of a table that kept its column positions.

    A record is a band of consecutive lines, opened by the line whose FIRST
    column holds a borrower reference and closed by the next such line. Every
    line of the band contributes to whichever columns it has text in, so a cell
    wrapped over five lines is read from those five lines and nothing else -
    which is the whole reason for locating columns rather than matching values.
    The previous parser searched the whole record for a known status word, and
    could only find the values it already had a word for.
    """
    spans = column_spans(table, table.section)
    if not spans:
        return []
    ref_a, ref_b = spans[0][1], spans[0][2]
    width = max([len(l) for l in table.data] + [1])
    bands, cur = [], None
    for line in table.data:
        padded = line.ljust(width)
        if ROW_START_RE.match(padded[ref_a:ref_b]):
            if cur:
                bands.append(cur)
            cur = [padded]
        elif cur is not None:
            cur.append(padded)
    if cur:
        bands.append(cur)

    rows = []
    for band in bands:
        row = {"section": table.section}
        for field, a, b in spans:
            pieces = []
            for line in band:
                cell = line[a:b]
                text = cell.rstrip()
                if not text.strip():
                    continue
                pieces.append((text.strip(), len(text) >= (b - a)))
            row[field] = _assemble(pieces)
        rows.append(row)
    return rows


# A collapsed rendition has no column positions, so the cells have to be told
# apart by what they contain. These are the shapes that are unambiguous.
LOAN_RE = re.compile(r"^\s*(IDA|IBRD|TF|GRANT|CREDIT|DON|PRET)\s*/\s*\S", re.I)
AMOUNT_TOKEN_RE = re.compile(r"[\d,]+\.\d{2}")
DATE_TOKEN_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
# The money line: whichever line carries the amounts. It does NOT begin with
# them - the narrow cells to their left pack onto the same line, so a real one
# reads "Post  Direct Selection  Direct  10,000.00  0.00  Canceled  2019-08-04".
# Requiring the line to start with an amount finds 39% of the records in a
# rendition where the true figure is 100%.
#
# What sits between the last amount and the first milestone date is the Process
# Status, in whatever language the plan is written in. That is also how the
# status vocabulary was mined in the first place, and it means this does not
# need to know the word to find the cell.


# Lines belonging to a column-heading band that the rendition reprints at every
# page break. They arrive in the MIDDLE of a record, because the page turned
# between that record's reference and its amounts, and read as data they put a
# heading inside a description and push the amounts out of the record entirely.
# A section heading starts a new table and is handled there; this is the band
# without its heading, which is not.
HEADER_NOISE_RE = re.compile(
    r"^\s*(Activity Reference No|Loan / Credit|Component\s*$|Review Type|Method\s*$|"
    r"Market Approac|Procurement Pro|Procureme\b|Prequalification|High SEA/SH|"
    r"Estimated Am|Actual Am|Process St|Draft Pre-qualification|Draft Bidding|"
    r"Specific Procurement|Bidding Documents|Proposal Submission|Bid Evaluation|"
    r"Signed Contract\s*$|Contract Complet|Terms of Reference\s*$|Expression of Interest|"
    r"Short List|Invitation to Identifie|Draft Negotiated|"
    r"(Planned|Actual)(\s+(Planned|Actual))*\s*$|Page \d+\s*$|"
    r"nt Docume|ount \(US\$|atus\s*$|cess\s*$|\(Y/N\)\s*$|isk\s*$|ation R)",
    re.I)


def strip_header_noise(lines):
    """Drop the reprinted column-heading band from a run of data lines."""
    return [l for l in lines if not HEADER_NOISE_RE.match(l)]


def _atoms(band):
    """A record's lines as a stream of typed tokens, in print order.

    Collapsed renditions come in shapes that look different and are not. One
    packs the narrow cells onto a line - "Post  Direct Selection  Direct
    10,000.00  0.00  Canceled  2019-08-04" - while another gives each cell its
    own line with blanks between. Read as lines those need two readers. Read as
    a stream of tokens they are the same thing in the same order, which is the
    only order STEP ever prints: the columns, left to right.

    Yields (kind, text) where kind is 'amount', 'date' or 'text'.
    """
    split = re.compile(r"([\d,]+\.\d{2}|\d{4}-\d{2}-\d{2})")
    for line in band:
        if not line.strip():
            continue
        for piece in split.split(line):
            piece = piece.strip()
            if not piece:
                continue
            if AMOUNT_TOKEN_RE.fullmatch(piece):
                yield "amount", piece
            elif DATE_TOKEN_RE.fullmatch(piece):
                yield "date", piece
            else:
                yield "text", piece


def read_collapsed_table(table, has_estimated=None):
    """Rows out of a rendition that threw its column positions away.

    Nothing can be sliced, so the reading is sequential: STEP emits the cells in
    column order and a record runs from one borrower reference to the next. The
    two cells that matter are found by their neighbours rather than by their
    content, which is what makes this work in any language - the amounts are
    the only tokens shaped like amounts, and the Process Status is whatever
    text sits between the last of them and the first milestone date.

    `has_estimated` says whether this table prints an Estimated Amount column.
    It matters and it cannot be guessed from the row: 19% of renditions are old
    enough that STEP printed only the actual amount, and on those the single
    figure is the actual. Read positionally without knowing that, an actual of
    0.00 is filed as an estimate of zero, which is worse than reading nothing.
    When not passed it is taken from the heading band, the only place that
    answers it.
    """
    if has_estimated is None:
        # Presence, not position. solve_columns orders the headings by x and a
        # collapsed band has no meaningful x - every label sits at the left
        # margin on its own line - so the increasing-x constraint there rejects
        # almost every column and would report the Estimated Amount heading
        # missing on a table that prints it.
        band = "\n".join(table.header)
        has_estimated = bool(_label_positions([band], "Estimated Amount (US$)"))

    bands, cur = [], None
    for line in table.data:
        if ROW_START_RE.match(line):
            if cur:
                bands.append(cur)
            cur = [line]
        elif cur is not None:
            cur.append(line)
    if cur:
        bands.append(cur)

    rows = []
    for raw_band in bands:
        # A heading band reprinted between this record's reference and its
        # figures means the page turned inside the record, and in these
        # renditions that is where the columns come apart: one Niger plan
        # prints the third row's description, then a heading, then the FIRST
        # row's amounts. Reading across that break attaches one package's money
        # to another package's reference, which is worse than reading nothing
        # because the result looks like data. Such a record keeps its reference
        # and its description and gives up its figures.
        interleaved = any(HEADER_NOISE_RE.match(l) for l in raw_band)
        band = strip_header_noise(raw_band)
        stream = list(_atoms(band))
        amounts = [i for i, (k, _) in enumerate(stream) if k == "amount"]
        row = {"section": table.section, "estimated_amount": "", "actual_amount": "",
               "status_raw": "", "loan": "", "dates": [], "block": "\n".join(band)}
        row["interleaved"] = interleaved
        if amounts and not interleaved:
            values = [stream[i][1] for i in amounts[:2]]
            if has_estimated and len(values) >= 2:
                row["estimated_amount"], row["actual_amount"] = values
            elif has_estimated:
                row["estimated_amount"] = values[0]
            else:
                row["actual_amount"] = values[0]
            # The status is the text between the last amount and the first date
            # after it. Stopping at the first date is what keeps a run of
            # milestone dates from being read as a status, and stopping at the
            # next amount is not needed because there is not another one.
            for kind, text in stream[amounts[-1] + 1:]:
                if kind == "date":
                    break
                if kind == "text" and text:
                    row["status_raw"] = text
                    break
        row["dates"] = [] if interleaved else [t for k, t in stream if k == "date"]
        loan = [t for k, t in stream if k == "text" and LOAN_RE.match(t)]
        row["loan"] = loan[0] if loan else ""
        # The description runs from the reference to the first structural cell.
        desc = []
        for kind, text in stream:
            if kind != "text" or LOAN_RE.match(text):
                break
            desc.append(text)
        row["description"] = " ".join(desc)
        rows.append(row)
    return rows


def collapsed_is_aligned(rows, floor=0.8):
    """Did the rendition keep its rows together, or scatter the columns?

    Some collapsed renditions emit each column of a page as its own run, so the
    reference column and the money column end up in different places and in
    different orders - one Niger plan prints the third row's description before
    the first row's amounts, and reading it by sequence attaches GS-2's figures
    to a different package entirely. That is the failure worth spending
    coverage to avoid: a package with no amount is a gap an older plan version
    can fill, while a package with someone else's amount is wrong and looks
    right.

    A rendition that kept its rows together puts a money line inside nearly
    every record; one that scattered them does not. The separation on the
    corpus is wide: the five intact renditions read 95.4% to 98.1%, the two
    scattered ones 23.2% and 53.2%. The floor sits in the gap, not near either
    side, so it is not a delicate choice - but it is a choice, and it spends
    Mozambique's 42 readable records to refuse its scattered ones. They are not
    lost: that project's older renditions keep their columns and parse.
    """
    if not rows:
        return True
    with_money = sum(1 for r in rows if r["estimated_amount"] or r["actual_amount"])
    return with_money / len(rows) >= floor
